apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-d
  name: myapp-d
  namespace: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp-d
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
