apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-d
  namespace: myapp
  labels:
    app: myapp-d
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: myapp-d
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70