apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-c
  namespace: myapp
  labels:
    app: myapp-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: myapp-c
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70