apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: myapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
    spec:
      automountServiceAccountToken: false
      containers:
      - name: myapp
        image: "tomcat:8.5-jre8"
        lifecycle:
          preStop:
            exec:
              # https://github.com/kubernetes/ingress-nginx/issues/3639
              command: ["/bin/bash", "-c", "sleep 3 && catalina.sh stop"]
        env:
        - name: JAVA_OPTS
          value: "-Xmx64m"
        ports:
        - containerPort: 8080
          name: default
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 115
          timeoutSeconds: 15
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 15
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3