---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret-ingress
  namespace: myapp
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.ingress.tls_cert | b64enc }}
  tls.key: {{ .Values.global.ingress.tls_key | b64enc }}