apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: myapp-cluster-admin
  namespace: myapp
subjects:
- kind: ServiceAccount
  name: myapp-cluster-admin
  namespace: myapp
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
