---
apiVersion: v1
kind: Secret
metadata:
  name: internal-tls-secret
  namespace: myapp
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.sidecars.tls_cert | b64enc }}
  tls.key: {{ .Values.global.sidecars.tls_key | b64enc }}