---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  myapp-internal-ca-root-public-crt
  namespace: myapp
binaryData:
  myapp-internal-ca-root-public.crt: {{ .Values.global.sidecars.tls_root_cert | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  myapp-internal-ca-root-public-crt
  namespace: ingress-nginx
binaryData:
  myapp-internal-ca-root-public.crt: {{ .Values.global.sidecars.tls_root_cert | b64enc }}
---