---
apiVersion: v1
kind: Secret
metadata:
  name: internal-tls-secret
  namespace: myapp-subdomain-{{ .Values.tenant }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.sidecar.tls_crt }}
  tls.key: {{ .Values.sidecar.tls_key }}