apiVersion: v1
kind: Service
metadata:
  name: myapp-{{ .Values.tenant }}
  namespace: myapp-subdomain-{{ .Values.tenant }}
  labels:
    app: myapp-{{ .Values.tenant }}
spec:
  type: ClusterIP
  selector:
    app: myapp-{{ .Values.tenant }}
  ports:
  - name: default
    port: 443
    protocol: TCP
    targetPort: 443
