kind: Namespace
apiVersion: v1
metadata:
  name: myapp-subdomain-{{ .Values.tenant }}
  labels:
    name: myapp-subdomain-{{ .Values.tenant }}
    tenant: "{{ .Values.tenant }}"
---
kind: Service
apiVersion: v1
metadata:
  name: myapp
  namespace: myapp-subdomain-{{ .Values.tenant }}
spec:
  type: ExternalName
  externalName: myapp.myapp.svc.cluster.local